#!/usr/bin/env python

import re
import sys
import argparse

import cartman.app
import cartman.exceptions


def main():
    application = cartman.app.CartmanApp()

    parser = argparse.ArgumentParser(prog="cm")
    parser.add_argument("command",
                        help="required (try commands)")
    parser.add_argument("parameters", nargs="*",
                        help="specific for each commands")
    parser.add_argument("-c", dest="add_comment", action="store_true",
                        help="add a comment via the editor (status)")
    parser.add_argument("-m", dest="comment", action="store",
                        help="comment to be added (status, comment)")
    parser.add_argument("-s", dest="stdin_id", action="store_true",
                        help="grab ticket_id from stdin")
    parser.add_argument("-a", dest="open_after", action="store_true",
                        help="open ticket in browser after command")
    args = parser.parse_args()

    # Try to grab the ticket id from stdin, if successful, slap the value as an
    # extra positional argument.
    if args.stdin_id:
        data = sys.stdin.read()
        m = re.match(".*#(\d+).*", data, flags=(re.MULTILINE|re.DOTALL))
        if not m:
            raise cartman.exceptions.UsageException("No id on stdin")

        args.append(m.group(1))

    try:
        application.run(args)
    except cartman.exceptions.UsageException, ex:
        sys.stderr.write("error: %s\n\n" % ex)
        parser.print_help(file=sys.stderr)
    except cartman.exceptions.FatalError, ex:
        sys.stderr.write("error: %s\n" % ex)
        sys.exit(1)

if __name__ == '__main__':
    main()
